apiVersion: "kubeflow.org/v1alpha1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-model_predictive_control-test-model-gpu-v35"
spec:
  backend: "tcp"
  masterPort: "23456"
  replicaSpecs:
    - replicas: 1
      replicaType: MASTER
      template:
        spec:
          containers:
          - image: gcr.io/proud-spring-222310/model_predictive_control_test:1351a3dadf711d304834a8c90a11688c77a97989
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "gs_key.json"
            - name: GCS_BUCKET 
              value: "model-predictive-control-test"
            imagePullPolicy: Always
            useHostIPC: true
            name: pytorch
            command: ["python3", "/project/src/main/python/train_model.py"]
            resources:
              limits:
                nvidia.com/gpu: 1
          restartPolicy: OnFailure
    - replicas: 1
      replicaType: WORKER
      template:
        spec:
          containers:
          - image: gcr.io/proud-spring-222310/model_predictive_control_test:1351a3dadf711d304834a8c90a11688c77a97989
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "gs_key.json"
            - name: GCS_BUCKET 
              value: "model-predictive-control-test"
            imagePullPolicy: Always
            useHostIPC: true
            name: pytorch
            command: ["python3", "/project/src/main/python/train_model.py"]
            resources:
              limits:
                nvidia.com/gpu: 1
          restartPolicy: OnFailure
