apiVersion: "kubeflow.org/v1alpha1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-mpc-test-model-cpu-v14"
spec:
  backend: "tcp"
  masterPort: "23456"
  replicaSpecs:
    - replicas: 1
      replicaType: MASTER
      template:
        spec:
          containers:
          - image: gcr.io/proud-spring-222310/mpc_test:b3f0ccd117082160b3f4a8d0c0ddd99607e422dc
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "gs_key.json"
            - name: GCS_BUCKET 
              value: "mpc-test"
            imagePullPolicy: Always 
            useHostIPC: true
            name: pytorch
            command: ["python3", "/project/src/main/python/train_model.py"]
            resources:
              limits:
                cpu: 0.5 
          restartPolicy: Never
    - replicas: 0
      replicaType: WORKER
      template:
        spec:
          containers:
          - image: gcr.io/proud-spring-222310/mpc_test:b3f0ccd117082160b3f4a8d0c0ddd99607e422dc
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "gs_key.json"
            - name: GCS_BUCKET 
              value: "mpc-test"
            imagePullPolicy: Always 
            useHostIPC: true
            name: pytorch
            resources:
              limits:
                cpu: 0.5
            command: ["python3", "/project/src/main/python/train_model.py"]
          restartPolicy: OnFailure
