apiVersion: "kubeflow.org/v1alpha1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-mpc-test-model-gpu-v22"
spec:
  backend: "tcp"
  masterPort: "23456"
  replicaSpecs:
    - replicas: 1
      replicaType: MASTER
      template:
        spec:
          containers:
          - image: gcr.io/proud-spring-222310/mpc_test:5a0a336954771a739bad2931a0bac523bbfa75fd
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "gs_key.json"
            - name: GCS_BUCKET 
              value: "mpc-test"
            imagePullPolicy: Always
            useHostIPC: true
            name: pytorch
            command: ["python3", "/project/src/main/python/train_model.py"]
            resources:
              limits:
                nvidia.com/gpu: 1
          restartPolicy: OnFailure
    - replicas: 3
      replicaType: WORKER
      template:
        spec:
          containers:
          - image: gcr.io/proud-spring-222310/mpc_test:5a0a336954771a739bad2931a0bac523bbfa75fd
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "gs_key.json"
            - name: GCS_BUCKET 
              value: "mpc-test"
            imagePullPolicy: Always
            useHostIPC: true
            name: pytorch
            command: ["python3", "/project/src/main/python/train_model.py"]
            resources:
              limits:
                nvidia.com/gpu: 1
          restartPolicy: OnFailure
