apiVersion: "kubeflow.org/v1alpha1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-tcp-dist-mpc-test-v4"
spec:
  backend: "tcp"
  masterPort: "23456"
  replicaSpecs:
    - replicas: 1
      replicaType: MASTER
      template:
        spec:
          containers:
          - image: gcr.io/proud-spring-222310/mpc_test:565910a4628cdbe6242189a8709c762ae39d97f4
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "gs_key.json"
            - name: MODEL_BUCKET 
              value: "mpc-test"
            imagePullPolicy: Always 
            useHostIPC: true
            name: pytorch
            command: ["python3", "/project/src/main/python/train_model.py"]
            resources:
              limits:
                cpu: 0.8 
          restartPolicy: Never
    - replicas: 1
      replicaType: WORKER
      template:
        spec:
          containers:
          - image: gcr.io/proud-spring-222310/mpc_test:565910a4628cdbe6242189a8709c762ae39d97f4
            imagePullPolicy: Always 
            useHostIPC: true
            name: pytorch
            resources:
              limits:
                cpu: 0.8
            command: ["python3", "/project/src/main/python/train_model.py"]
          restartPolicy: OnFailure
