apiVersion: "kubeflow.org/v1alpha1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-tcp-dist-mpc-test-v6"
spec:
  backend: "tcp"
  masterPort: "23456"
  replicaSpecs:
    - replicas: 1
      replicaType: MASTER
      template:
        spec:
          containers:
          - image: gcr.io/t-pulsar-217904/mpc_test
            imagePullPolicy: IfNotPresent
            name: pytorch
            command: ["python3", "/project/src/main/python/train_policy.py"]
            resources:
              limits:
                cpu: "1"
                nvidia.com/gpu: 1
          restartPolicy: OnFailure
    - replicas: 0
      replicaType: WORKER
      template:
        spec:
          containers:
          - image: gcr.io/t-pulsar-217904/mpc_test
            imagePullPolicy: IfNotPresent
            name: pytorch
            command: ["python3", "/project/src/main/python/train_policy.py"]
            resources:
              limits:
                cpu: "1"
                nvidia.com/gpu: 1
          restartPolicy: OnFailure
